### ISSUE TITLE
Server Error when use theme inheritance

### ISSUE THREAD

**Issue by akhyarrh** [getgrav/grav-theme-cacti#20]
Ref.: https://getgrav.org/blog/theme-development-with-inheritance

Based on that post I setup inheritance:

```yaml
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/mytheme
         - user/themes/cacti
```
```yaml
pages:
 theme: mytheme
```

Run `php -S localhost:8000 system/router.php`  , go to `http://localhost:8000/`,throw `400 - Template "post-list.html.twig" is not defined.`
