### ISSUE TITLE
How to change footer 'your company'

### ISSUE THREAD

**Issue by Seferi** [getgrav/grav-theme-cacti#23]
Hi,
I was able to customize everything except two things, the footer where it says 'Your Company' and 'Blogging about stuff'
I appreciate if you can direct me to the path where I can edit these. Thanks.

**Comment by romanbeldacz** [comment]
Hi,
i found these things are customized here: user/themes/cacti/languages.yaml
This is multi-language page, so it's defined for lot's of languages.

**Comment by ricardo118** [comment]
Yeah it is defined in that file. However if you dont want to modify the theme directly, you can override these by adding a file in `user/languages/en.yaml` en.yaml is an example, you should use whatever language code you want to override. Inside the file you can populate with:

```yaml
SITE:
    TITLE: My overrides
    DESCRIPTION: Blogging about stuff
    COPYRIGHT: © Copyright %s Your Company
```

This will override the themes values with your own without changing the original one
